### PR TITLE
Preview in Giphy Picker

### PR DESCRIPTION
**Pull request by shiki**
dec-02-2018 07-15-15

This is a part of the Giphy picker feature (wordpress-mobile#8627). It adds previewing of GIFs using the _Preview_ button or long pressing a single GIF.

- The `develop` branch from [wordpress-mobile/WordPress-Android](/wordpress-mobile/WordPress-Android/tree/develop) was merged before the changes. Merge commit is c79ba5f.
- The Preview-related changes start from commit 624d1d7.
- Preview functionality uses the existing `MediaPreviewActivity`

### Testing 

1. Create a [Giphy API key](https://developers.giphy.com/docs/) and paste it in your `gradle.properties` as the value for `wp.giphy.api_key`
2. Go to the Media Library and click on the _Add_ button at the top right. Select the _Choose from Giphy_ option.
3. In the Giphy picker, perform a search and select some items.
4. Press the _Preview_ button. The selected GIFs should be shown on a different page. 

Also, try long pressing on a single GIF.

### CODE REVIEW

**Comment by kwonye** [comment]
@shiki hey! This is the only one left that I have. Can you re-do this by merging in the gutenberg work to the feature `issue/8627-giphy` and then open a PR against it please? With so many changes it's hard to decipher filter out your changes vs the merge. Thanks in advance!

**Comment by kwonye** [comment]
Actually @shiki I don't think you have to un-do this PR. Simply merging in `develop` to `issue/8627-giphy` may make all the other commits go away for all PRs.

**Comment by kwonye** [comment]
Yes, as I tried to merge all the branches into a single one to test fully, I ran into this issue (issue/8627-giphy-tracking)

All branches are good to merge individually but it looks like we have to handle these merge conflicts one-by-one. Just ping me when you're done with a merge conflict and I'll kick off the next issue!

**Comment by shiki** [comment]
@kwonye I fixed the conflicts for this PR.

**Comment by kwonye** [comment]
Thanks! Merged. I'll do a final final spot check with the final feature branch before it's merged into develop

**Comment by shiki** [comment]
> Thanks! Merged. I'll do a final final spot check with the final feature branch before it's merged into develop

I can create a final pull request if that will help.

**Pull request merged**
