### PR TITLE
Giphy Picker: Search While Typing

### PR DESCRIPTION
**Pull request by shiki**
dec-07-2018 19-07-36

This is a part of the Giphy picker feature (wordpress-mobile/WordPress-Android#8627). It changes the search so that search is automatically performed when the user pauses or stops typing. Pressing _Enter_ on the keyboard just dismisses the keyboard now.

The circular progress indicator is also now shown when performing an initial page load. For subsequent page loads, I believe it's not necessary because our `PagedList` is designed to show placeholders for all the unloaded pages.

The `develop` branch from [wordpress-mobile/WordPress-Android](/wordpress-mobile/WordPress-Android/tree/develop) was merged before the changes. Merge commit is 1a9a379. The first commit for implementing this feature is 97309e1.

### Testing

1. Create a [Giphy API key](https://developers.giphy.com/docs/) and paste it in your `gradle.properties` as the value for `wp.giphy.api_key`
2. Go to the Media Library and click on the _Add_ button at the top right. Select the _Choose from Giphy_ option.
3. In the Giphy Picker, typing anything in the search bar

### CODE REVIEW

**Comment by shiki** [comment]
Merged the main branch [issue/8627-giphy](/shiki/WordPress-Android/tree/issue/8627-giphy) and changed the target branch of this PR.

**Comment by kwonye** [comment]
Last one, @shiki before we can do the final merge! Yes, please do a final PR to the main repo from the main feature branch!

**Comment by shiki** [comment]
@kwonye This is now ready for review. I also found a bug and fixed it in 2c3f2fd.

**Comment by kwonye** [comment]
That's perfect, thanks! :shipit:

**Pull request merged**
